name: MultipleJobs
on: push
env:
  username: Shreyal
  super_duper_var: totally_awesome

jobs:
  windows_job:
    runs-on: windows-latest
    steps:
      - run: echo 'Hi ${{ env.username }}'  # Hi Shreyal
      - run: echo 'Hi ${{ env.username }}'  # Hi Shah
        env:
          username: Shah
  linux_job:
    runs-on: ubuntu-latest
    env:
      username: SS
    steps:
      - run: echo 'Hi ${{ env.username }}'  # Hi Tux
